"""wiki/index.md generator (docs/design.md §7, §9) — the agent's first read on any query."""

from __future__ import annotations

from pathlib import Path

from notion_wiki.graph.scanner import WikiPage, scan_wiki_pages
from notion_wiki.paths import wiki_index_path


def render_index(pages: list[WikiPage]) -> str:
    groups: dict[str, list[WikiPage]] = {}
    for page in pages:
        groups.setdefault(page.type or "untyped", []).append(page)

    lines = ["# Wiki Index", "", "_Generated by `notion-wiki graph` — do not edit by hand._"]
    for type_name in sorted(groups):
        lines.append("")
        lines.append(f"## {type_name}")
        lines.append("")
        for page in sorted(groups[type_name], key=lambda p: p.rel_path):
            title = page.frontmatter.get("title") or Path(page.rel_path).stem
            link = page.rel_path[: -len(".md")]
            entry = f"- [[{link}]] — {title}"
            if page.description:
                entry += f": {page.description}"
            lines.append(entry)

    return "\n".join(lines).rstrip() + "\n"


def generate_index(wiki_root: Path) -> str:
    pages = scan_wiki_pages(wiki_root)
    content = render_index(pages)
    path = wiki_index_path(wiki_root)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")
    return content
