"""notionwiki CLI (docs/design.md §8, §8.2). Entry points: `notionwiki`, `nw`."""

from __future__ import annotations

import itertools
import json as jsonlib
import re
import sys
from datetime import UTC, datetime
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel

from notion_wiki import __version__
from notion_wiki.config import Config, DatabaseRef, config_exists, load_config, save_config
from notion_wiki.ingest.daemon_log import DaemonLog
from notion_wiki.ingest.pull import PullRunner
from notion_wiki.notion.client import NotionClient
from notion_wiki.paths import (
    config_path,
    daemon_log_path,
    ensure_wiki_scaffold,
    get_state_dir,
    lock_path,
    state_db_path,
)
from notion_wiki.raw_index import find_source, list_raw_sources
from notion_wiki.schedule.base import detect_scheduler
from notion_wiki.store.db import StateDB
from notion_wiki.token import get_token, set_token

BRAND = "notionwiki"

app = typer.Typer(add_completion=False, no_args_is_help=True)
service_app = typer.Typer(add_completion=False, help="Manage the scheduled notionwiki pull")
app.add_typer(service_app, name="service")
config_app = typer.Typer(
    add_completion=False,
    no_args_is_help=True,
    help="View or update saved settings (token, pages, databases) without re-running init",
)
app.add_typer(config_app, name="config")


def _force_utf8_output() -> None:
    """Windows consoles default to a legacy cp1252 codec that cannot encode the
    checkmarks/arrows in our output — writing `✓` raises UnicodeEncodeError and
    aborts the command (worst when stdout is piped). Reconfigure both streams to
    UTF-8, with errors="replace" so an exotic terminal degrades gracefully
    instead of crashing."""
    for stream in (sys.stdout, sys.stderr):
        reconfigure = getattr(stream, "reconfigure", None)
        if reconfigure is not None:
            try:
                reconfigure(encoding="utf-8", errors="replace")
            except (ValueError, OSError):
                pass


_force_utf8_output()
console = Console()


def _humanize_age(iso_timestamp: str | None) -> str:
    if not iso_timestamp:
        return "never"
    then = datetime.fromisoformat(iso_timestamp.replace("Z", "+00:00"))
    now = datetime.now(UTC)
    delta = now - then
    seconds = int(delta.total_seconds())
    if seconds < 60:
        return "just now"
    if seconds < 3600:
        return f"{seconds // 60}m ago"
    if seconds < 86400:
        return f"{seconds // 3600}h ago"
    return f"{seconds // 86400}d ago"


def _status_line(config: Config) -> str | None:
    try:
        db = StateDB(state_db_path())
    except Exception:
        return None
    try:
        count = len([p for p in db.all_pages() if not p.deleted])
        baseline = db.get_meta("last_incremental_baseline")
    finally:
        db.close()
    return f"Status  {count} sources · last pull {_humanize_age(baseline)}"


def _print_banner() -> None:
    lines = [f"[bold]✻ Welcome to {BRAND}[/bold]", "", f"Notion → LLM Wiki bridge · v{__version__}"]
    if config_exists():
        config = load_config()
        lines.append(f"Wiki    {config.wiki_root}")
        status_line = _status_line(config)
        if status_line:
            lines.append(status_line)
    console.print(Panel("\n".join(lines), expand=False))
    console.print()
    console.print(" Try: notionwiki pull        sync from Notion now")
    console.print("      notionwiki graph       open the wiki map at localhost:7777")
    console.print("      notionwiki status      ingestion health")


def _banner_suppressed(argv: list[str]) -> bool:
    """Banner suppression rules (§8.2): never on --json/--quiet/non-TTY output —
    the tool runs unattended, so scheduled pulls must log clean, parseable lines."""
    if "--json" in argv or "--quiet" in argv or "-q" in argv:
        return True
    return not sys.stdout.isatty()


def main() -> None:
    """Console-script entry point. Wraps `app()` to show the welcome banner on the
    bare invocation, `init`, and `--help` (§8.2) — cases Typer's own dispatch
    doesn't give us an easy hook into."""
    argv = sys.argv[1:]
    show_on = not argv or "--help" in argv or "-h" in argv or (argv and argv[0] == "init")
    if show_on and not _banner_suppressed(argv):
        _print_banner()
        if not argv:
            return
    app()


_AGENT_DOC_TEMPLATE = """# {filename}

This is the root of an LLM Wiki fed by notionwiki. Ingestion history lives in
`raw/notion/daemon_log.md`.

## Layers

- `raw/` — Layer 1, immutable source documents. One subfolder per feeder; `raw/notion/` is
  owned by the ingestion bridge and is **read-only to agents by convention**. Cite it via
  `sources: ["[[raw/notion/<slug>]]"]` frontmatter on wiki pages — never edit files under `raw/`.
- `wiki/` — Layer 2, agent-built and agent-owned.
  - `wiki/index.md` — master catalog (generated by `notionwiki graph`)
  - `wiki/graph.json` — link graph (generated by `notionwiki graph`)
  - `wiki/log.md` — narrative operation log (agent-owned)
  - `wiki/overview.md` — high-level synthesis
  - `wiki/concepts/`, `wiki/entities/`, `wiki/sources/` — page types: concept, entity,
    source-summary
- `outputs/` — generated reports/answers: products *of* the wiki, not part of it.

## Rules

- Prefer editing an existing wiki page over creating a near-duplicate; create a new page only
  when no existing page owns the topic.
- Compression rule: a wiki page larger than its source has negative value — synthesize, don't copy.
- Never edit `raw/`. Only the notionwiki ingestion daemon writes there.
- Keep `CLAUDE.md` and `AGENTS.md` as identical twins — mirror an edit to one into the other.

## CLI

`notionwiki pull` (force a sync), `notionwiki status` (ingestion health), `notionwiki graph`
(regenerate index/graph.json + serve the graph UI), `notionwiki open <page>` (look up a source).
There is no `sync`/`push` — this bridge is pull-only.
"""


def _seed_agent_docs(wiki_root: Path) -> None:
    for filename in ("CLAUDE.md", "AGENTS.md"):
        path = wiki_root / filename
        if not path.exists():
            path.write_text(_AGENT_DOC_TEMPLATE.format(filename=filename), encoding="utf-8")


def _extract_page_id_from_url(url: str) -> str:
    stripped = url.replace("-", "")
    match = re.search(r"([0-9a-fA-F]{32})(?:[?#]|$)", stripped)
    if not match:
        return url.strip()
    raw = match.group(1)
    return f"{raw[0:8]}-{raw[8:12]}-{raw[12:16]}-{raw[16:20]}-{raw[20:32]}"


def _database_title(db: dict) -> str:
    return "".join(rt.get("plain_text", "") for rt in db.get("title", [])) or "Untitled database"


_tui_state: bool | None = None


def _tui_available() -> bool:
    """Whether the questionary/prompt_toolkit TUI can actually run here.

    A plain `isatty()` check isn't enough: on Git Bash / mintty on Windows the
    stream is a tty but prompt_toolkit raises NoConsoleScreenBufferError. We
    probe once (creating a prompt_toolkit output) and cache the result; piped
    input (tests, CI, `init < answers.txt`) and unsupported terminals both fall
    back to line prompts."""
    global _tui_state
    if _tui_state is not None:
        return _tui_state
    if not (sys.stdin.isatty() and sys.stdout.isatty()):
        _tui_state = False
        return False
    try:
        from prompt_toolkit.output.defaults import create_output

        create_output()
        _tui_state = True
    except Exception:  # noqa: BLE001 - any probe failure means "no TUI, use fallback"
        _tui_state = False
    return _tui_state


def _disable_tui() -> None:
    """Latch the TUI off after a runtime failure so we don't retry it per prompt."""
    global _tui_state
    _tui_state = False


def _mask_secret(secret: str) -> str:
    secret = secret.strip()
    if not secret:
        return "(empty)"
    if len(secret) <= 8:
        return "*" * len(secret)
    return f"{secret[:4]}...{secret[-4:]} ({len(secret)} chars)"


# A subtle step marker replaces questionary's default "?" so each line reads as
# a single clean prompt; the same marker prefixes the non-TTY line-prompt fallback.
def _flabel(qmark: str, label: str) -> str:
    return f"{qmark} {label}"


def _ask_path(label: str, default: str, *, qmark: str = "›") -> Path:
    if _tui_available():
        try:
            import questionary

            answer = questionary.path(
                label, default=default, only_directories=True, qmark=qmark
            ).ask()
            if answer is None:
                raise typer.Abort()
            return Path(answer.strip() or default).expanduser()
        except typer.Abort:
            raise
        except Exception:  # noqa: BLE001 - degrade to a line prompt
            _disable_tui()
    return Path(typer.prompt(_flabel(qmark, label), default=default)).expanduser()


def _ask_token(label: str, *, qmark: str = "›") -> str:
    if _tui_available():
        try:
            import questionary

            token = questionary.password(label, qmark=qmark).ask()
            if token is None:
                raise typer.Abort()
            return token.strip()
        except typer.Abort:
            raise
        except Exception:  # noqa: BLE001 - degrade to a line prompt
            _disable_tui()
    return typer.prompt(_flabel(qmark, label), hide_input=True).strip()


def _confirm(label: str, *, default: bool = True, qmark: str = "›") -> bool:
    if _tui_available():
        try:
            import questionary

            answer = questionary.confirm(
                label, default=default, auto_enter=False, qmark=qmark
            ).ask()
            return default if answer is None else bool(answer)
        except Exception:  # noqa: BLE001 - degrade to a line prompt
            _disable_tui()
    return typer.confirm(_flabel(qmark, label), default=default)


_ALL = "__all__"
_PASTE = "__paste__"
_PAGE_PICKER_LIMIT = 200


def _ordered_page_tree(pages: list) -> list[tuple[object, int]]:
    """Order pages as a parent→child tree (each with a depth) so the picker reads
    as a hierarchy instead of a flat, arbitrarily-sorted list. Pages whose parent
    isn't among the shared set are treated as top-level roots; any left unvisited
    (cycles/orphans) are appended so nothing is dropped."""
    by_id = {p.id: p for p in pages}
    children: dict[str | None, list] = {}
    for p in pages:
        parent = p.parent_id if (p.parent_type == "page_id" and p.parent_id in by_id) else None
        children.setdefault(parent, []).append(p)

    ordered: list[tuple[object, int]] = []
    seen: set[str] = set()

    def walk(parent: str | None, depth: int) -> None:
        for p in sorted(children.get(parent, []), key=lambda x: (x.title or "").lower()):
            if p.id in seen:
                continue
            seen.add(p.id)
            ordered.append((p, depth))
            walk(p.id, depth + 1)

    walk(None, 0)
    ordered += [(p, 0) for p in pages if p.id not in seen]
    return ordered


def _select_scope_pages(candidates: list, *, qmark: str = "›") -> list[str]:
    """Pages to scope ingestion to; [] means "all pages shared with the integration"."""
    if _tui_available():
        try:
            import questionary

            choices: list = [
                questionary.Choice(
                    "All pages shared with the integration", value=_ALL, checked=True
                )
            ]
            if candidates:
                choices.append(questionary.Separator())
                for page, depth in _ordered_page_tree(candidates):
                    title = ("  " * depth) + (page.title or "(untitled)")
                    choices.append(questionary.Choice(title, value=page.id))
            choices.append(questionary.Separator())
            choices.append(questionary.Choice("Paste a page URL...", value=_PASTE))
            picked = questionary.checkbox(
                "Which pages should the wiki pull?  (space toggles, enter confirms)",
                choices=choices,
                qmark=qmark,
            ).ask()
            if picked is None:
                raise typer.Abort()
            if _ALL in picked or not picked:
                return []
            ids = [v for v in picked if v not in (_ALL, _PASTE)]
            if _PASTE in picked:
                url = (questionary.text("Page URL").ask() or "").strip()
                if url:
                    ids.append(_extract_page_id_from_url(url))
            return ids
        except typer.Abort:
            raise
        except Exception:  # noqa: BLE001 - degrade to the numbered fallback
            _disable_tui()

    # Non-interactive fallback: numbered list, comma-separated, or "all".
    for i, page in enumerate(candidates, start=1):
        console.print(f"   [{i}] {page.title}")
    paste_index = len(candidates) + 1
    console.print(f"   [{paste_index}] paste a page URL")
    choice = typer.prompt("   Pages to pull (comma-separated numbers, or 'all')", default="all")
    if choice.strip().lower() in ("all", ""):
        return []
    ids = []
    for part in choice.split(","):
        part = part.strip()
        if not part.isdigit():
            continue
        idx = int(part)
        if 1 <= idx <= len(candidates):
            ids.append(candidates[idx - 1].id)
        elif idx == paste_index:
            ids.append(_extract_page_id_from_url(typer.prompt("   Page URL")))
    return ids


def _select_databases(raw_databases: list[dict], *, qmark: str = "›") -> list[DatabaseRef]:
    if _tui_available():
        try:
            import questionary

            choices = [questionary.Choice("All databases", value=_ALL, checked=True)]
            choices += [
                questionary.Choice(_database_title(db), value=db["id"]) for db in raw_databases
            ]
            picked = questionary.checkbox(
                "Which databases should the wiki pull?  (space toggles, enter confirms)",
                choices=choices,
                qmark=qmark,
            ).ask()
            if picked is None:
                raise typer.Abort()
            if _ALL in picked or not picked:
                selected = raw_databases
            else:
                wanted = set(picked)
                selected = [db for db in raw_databases if db["id"] in wanted]
            return [DatabaseRef(id=db["id"], name=_database_title(db)) for db in selected]
        except typer.Abort:
            raise
        except Exception:  # noqa: BLE001 - degrade to the [all/choose] fallback
            _disable_tui()

    # Non-interactive fallback: the original [all/choose] text flow.
    console.print(f"   Found {len(raw_databases)} databases — pull all, or choose?")
    choice = typer.prompt("   [all/choose]", default="all")
    if choice.strip().lower().startswith("c"):
        return _prompt_choose_databases(raw_databases)
    return [DatabaseRef(id=db["id"], name=_database_title(db)) for db in raw_databases]


def _prompt_choose_databases(raw_databases: list[dict]) -> list[DatabaseRef]:
    for i, db in enumerate(raw_databases, start=1):
        console.print(f"   [{i}] {_database_title(db)}")
    choice = typer.prompt("   Choose (comma-separated numbers)", default="1")
    indices = {int(part.strip()) for part in choice.split(",") if part.strip().isdigit()}
    return [
        DatabaseRef(id=db["id"], name=_database_title(db))
        for i, db in enumerate(raw_databases, start=1)
        if i in indices
    ]


@app.command()
def init() -> None:
    """Interactive setup wizard (§8.1): wiki location, token, root page, databases, schedule."""
    from notion_wiki.notion.models import Page

    console.print("[bold]notionwiki setup[/bold]\n")

    existing = load_config() if config_exists() else None
    default_root = str(existing.wiki_root) if existing else str(Path.home() / ".notionwiki")

    wiki_root = _ask_path(
        "Where should the wiki live? (defaults to this location)", default_root, qmark="1"
    )

    token = _ask_token("Paste your Notion integration token", qmark="2")
    client = NotionClient(token)
    try:
        pages = [
            Page.from_api(raw) for raw in itertools.islice(client.search(), _PAGE_PICKER_LIMIT)
        ]
    except Exception as exc:  # noqa: BLE001 - surfaced directly to the operator
        console.print(f"[red]Could not validate token:[/red] {exc}")
        raise typer.Exit(1) from exc
    console.print(f"  [green]token valid[/green]  [dim]{_mask_secret(token)}[/dim]")

    # Database rows surface as pages with a database parent; they belong to the
    # database step (§5.2), not the page-scope picker.
    page_candidates = [p for p in pages if p.parent_type != "database_id"]
    console.print(
        "[dim]Keep 'All ...' selected to pull everything shared, or pick specific pages — "
        "their sub-pages are always included.[/dim]"
    )
    if len(pages) >= _PAGE_PICKER_LIMIT:
        console.print(
            f"  [dim]Showing the first {_PAGE_PICKER_LIMIT} shared pages; "
            "use 'All ...' or paste a URL if one isn't listed.[/dim]"
        )
    root_page_ids = _select_scope_pages(page_candidates, qmark="3")

    databases: list[DatabaseRef] = []
    if _confirm("Also pull databases?", default=True, qmark="4"):
        raw_databases = list(itertools.islice(client.search_databases(), 25))
        if raw_databases:
            databases = _select_databases(raw_databases, qmark="4")
        else:
            console.print("  [dim]No databases shared with the integration.[/dim]")

    interval_minutes = max(1, typer.prompt("5 Pull interval in minutes", default=1, type=int))

    install_schedule = _confirm("Install the background schedule now?", default=True, qmark="6")

    config = Config(
        wiki_root=wiki_root,
        root_page_ids=root_page_ids,
        databases=databases,
        interval_minutes=interval_minutes,
    )
    save_config(config)
    set_token(token)
    ensure_wiki_scaffold(wiki_root)
    _seed_agent_docs(wiki_root)
    client.close()

    console.print(f"\n[green]Wrote config to[/green] {config_path()}")
    console.print(
        f"[green]Scaffolded wiki at[/green] {wiki_root} "
        "(raw/notion/, wiki/, outputs/, CLAUDE.md/AGENTS.md)"
    )

    if install_schedule:
        scheduler = detect_scheduler()
        warnings = scheduler.install(interval_minutes)
        console.print(
            f"[green]Registered[/green] {scheduler.name} schedule (every {interval_minutes} min)."
        )
        for warning in warnings:
            console.print(f"[yellow]Warning:[/yellow] {warning}")

    console.print(
        "\nRun `notionwiki pull` for a first sync, or point your assistant at the wiki root."
    )


@service_app.command("install")
def service_install(
    interval_minutes: int | None = typer.Option(
        None, "--interval", help="Override the configured interval (minutes)"
    ),
) -> None:
    """Register scheduled `notionwiki pull` with the OS scheduler (§10)."""
    if not config_exists():
        console.print("[red]Not initialized.[/red] Run `notionwiki init` first.")
        raise typer.Exit(1)
    config = load_config()
    interval = interval_minutes or config.interval_minutes
    scheduler = detect_scheduler()
    warnings = scheduler.install(interval)
    console.print(f"[green]Installed[/green] {scheduler.name} schedule (every {interval} min).")
    for warning in warnings:
        console.print(f"[yellow]Warning:[/yellow] {warning}")


@service_app.command("uninstall")
def service_uninstall() -> None:
    """Remove the scheduled `notionwiki pull`."""
    scheduler = detect_scheduler()
    scheduler.uninstall()
    console.print(f"[green]Uninstalled[/green] {scheduler.name} schedule.")


@service_app.command("status")
def service_status() -> None:
    """Report whether the scheduled pull is installed."""
    scheduler = detect_scheduler()
    status = scheduler.status()
    if status.installed:
        console.print(f"[green]Installed[/green] ({scheduler.name}): {status.detail}")
    else:
        console.print(f"[yellow]Not installed[/yellow] ({scheduler.name}): {status.detail}")


def _require_config() -> Config:
    if not config_exists():
        console.print("[red]Not initialized.[/red] Run `notionwiki init` first.")
        raise typer.Exit(1)
    return load_config()


def _require_client() -> NotionClient:
    token = get_token()
    if not token:
        console.print(
            "[red]No Notion token found.[/red] Run `notionwiki config token` "
            "or set NOTION_WIKI_TOKEN."
        )
        raise typer.Exit(1)
    return NotionClient(token)


@config_app.command("show")
def config_show() -> None:
    """Print the current settings."""
    config = _require_config()
    scope = (
        f"{len(config.root_page_ids)} selected page(s) (+ sub-pages)"
        if config.root_page_ids
        else "all pages shared with the integration"
    )
    dbs = ", ".join(db.name for db in config.databases) or "none"
    console.print("[bold]notionwiki config[/bold]")
    console.print(f"  wiki root   {config.wiki_root}")
    console.print(f"  token       {'[green]set[/green]' if get_token() else '[red]not set[/red]'}")
    console.print(f"  page scope  {scope}")
    console.print(f"  databases   {dbs}")
    console.print(f"  interval    {config.interval_minutes} min")


@config_app.command("token")
def config_token() -> None:
    """Replace the stored Notion integration token."""
    _require_config()
    token = _ask_token("Paste your new Notion integration token")
    client = NotionClient(token)
    try:
        next(iter(client.search()), None)  # validates auth
    except Exception as exc:  # noqa: BLE001 - surfaced directly to the operator
        console.print(f"[red]Could not validate token:[/red] {exc}")
        raise typer.Exit(1) from exc
    finally:
        client.close()
    set_token(token)
    console.print(f"[green]✓ Token updated[/green]  [dim]{_mask_secret(token)}[/dim]")


@config_app.command("pages")
def config_pages() -> None:
    """Re-select which pages (and their sub-pages) to pull."""
    from notion_wiki.notion.models import Page

    config = _require_config()
    client = _require_client()
    try:
        pages = [
            Page.from_api(raw) for raw in itertools.islice(client.search(), _PAGE_PICKER_LIMIT)
        ]
    finally:
        client.close()
    candidates = [p for p in pages if p.parent_type != "database_id"]
    config.root_page_ids = _select_scope_pages(candidates, qmark="›")
    save_config(config)
    scope = f"{len(config.root_page_ids)} page(s)" if config.root_page_ids else "all shared pages"
    console.print(
        f"[green]✓ Page scope updated[/green] — {scope}.  "
        "[dim]Run `notionwiki pull --full` to apply.[/dim]"
    )


@config_app.command("databases")
def config_databases() -> None:
    """Re-select which databases to pull."""
    config = _require_config()
    client = _require_client()
    try:
        raw_databases = list(itertools.islice(client.search_databases(), 50))
    finally:
        client.close()
    if not raw_databases:
        console.print("[yellow]No databases shared with the integration.[/yellow]")
        config.databases = []
    else:
        config.databases = _select_databases(raw_databases, qmark="›")
    save_config(config)
    names = ", ".join(db.name for db in config.databases) or "none"
    console.print(
        f"[green]✓ Databases updated[/green] — {names}.  "
        "[dim]Run `notionwiki pull --full` to apply.[/dim]"
    )


@app.command()
def daemon(
    interval_seconds: float = typer.Option(
        60.0, "--interval-seconds", help="Pull cadence in seconds"
    ),
    serve_graph: bool = typer.Option(
        False, "--serve-graph", help="Co-host the graph UI in this process"
    ),
    graph_port: int = typer.Option(7777, "--graph-port"),
) -> None:
    """Optional long-lived pull loop (§10) — an alternative to `service install`."""
    if not config_exists():
        console.print("[red]Not initialized.[/red] Run `notionwiki init` first.")
        raise typer.Exit(1)
    config = load_config()
    token = get_token()
    if not token:
        console.print(
            "[red]No Notion token found.[/red] Run `notionwiki init` or set NOTION_WIKI_TOKEN."
        )
        raise typer.Exit(1)

    from notion_wiki.daemon import run_forever

    console.print(f"[green]Running[/green] every {interval_seconds}s (Ctrl+C to stop).")
    run_forever(
        config,
        token,
        get_state_dir(),
        interval_seconds=interval_seconds,
        serve_graph=serve_graph,
        graph_port=graph_port,
    )


@app.command()
def graph(
    serve: bool = typer.Option(False, "--serve", help="Also serve the graph UI at localhost:7777"),
    port: int = typer.Option(7777, "--port", help="Port for the graph UI"),
) -> None:
    """Regenerate wiki/index.md + wiki/graph.json, and optionally serve the graph UI (§9)."""
    if not config_exists():
        console.print("[red]Not initialized.[/red] Run `notionwiki init` first.")
        raise typer.Exit(1)
    config = load_config()

    from notion_wiki.graph.graph_gen import generate_graph
    from notion_wiki.graph.index_gen import generate_index

    generate_index(config.wiki_root)
    graph_data = generate_graph(config.wiki_root)
    node_count = len(graph_data["nodes"])
    console.print(
        f"[green]✓ Regenerated[/green] wiki/index.md and wiki/graph.json "
        f"[dim]({node_count} nodes, {len(graph_data['edges'])} edges)[/dim]"
    )
    if node_count == 0:
        console.print(
            "  [dim]The graph maps the agent-built [italic]wiki/[/italic] layer, which is still "
            "empty — pull sources with `notionwiki pull`, then have your assistant build "
            "wiki pages from them.[/dim]"
        )

    if serve:
        try:
            from notion_wiki.graph.server import serve as serve_graph
        except ImportError:
            console.print(
                "[red]The graph UI needs the 'graph' extra (fastapi/uvicorn).[/red] "
                "Reinstall with `uv tool install 'notionwiki[graph]'`, or run `pip install "
                "'fastapi' 'uvicorn'` in the runtime."
            )
            raise typer.Exit(1) from None

        url = f"http://127.0.0.1:{port}/graph"
        console.print(
            f"[green]Serving graph UI[/green] at [link={url}]{url}[/link]  "
            "[dim](Ctrl+C to stop)[/dim]"
        )
        import webbrowser

        webbrowser.open(url)
        serve_graph(config.wiki_root, port=port)


@app.command()
def lint() -> None:
    """Agent-run lint pass over the wiki layer (§7): orphans, dangling links, drift."""
    if not config_exists():
        console.print("[red]Not initialized.[/red] Run `notionwiki init` first.")
        raise typer.Exit(1)
    config = load_config()

    from notion_wiki.graph.lint import run_lint

    issues = run_lint(config.wiki_root)
    if not issues:
        console.print("[green]No lint issues found.[/green]")
        return

    console.print(f"[yellow]{len(issues)} issue(s) found:[/yellow]")
    for issue in issues:
        console.print(f"  [{issue.kind}] {issue.page}: {issue.detail}")
    raise typer.Exit(1)


@app.command()
def pull(
    full: bool = typer.Option(False, "--full", help="Force a full reconciliation sweep"),
    json_output: bool = typer.Option(False, "--json", help="Machine-readable output"),
) -> None:
    """Force an immediate pull/convert/write cycle (ingestion)."""
    if not config_exists():
        console.print("[red]Not initialized.[/red] Run `notionwiki init` first.")
        raise typer.Exit(1)

    config = load_config()
    token = get_token()
    if not token:
        console.print(
            "[red]No Notion token found.[/red] Run `notionwiki init` or set NOTION_WIKI_TOKEN."
        )
        raise typer.Exit(1)

    state_dir = get_state_dir()
    client = NotionClient(token)
    db = StateDB(state_db_path(state_dir))
    try:
        runner = PullRunner(
            client,
            config.wiki_root,
            db,
            lock_path=lock_path(state_dir),
            state_dir=state_dir,
        )
        stats = runner.run(
            full=full,
            databases=config.database_pairs(),
            root_page_ids=config.root_page_ids,
        )
    finally:
        db.close()
        client.close()

    if stats.skipped:
        if json_output:
            typer.echo(jsonlib.dumps({"skipped": True}))
        else:
            console.print("[yellow]Skipped[/yellow] — another notionwiki pull is already running.")
        return

    if json_output:
        typer.echo(
            jsonlib.dumps(
                {
                    "new": stats.new,
                    "updated": stats.updated,
                    "unchanged": stats.unchanged,
                    "renamed": stats.renamed,
                    "archived": stats.archived,
                    "settling": stats.settling,
                    "errors": stats.errors,
                }
            )
        )
        return

    parts = []
    if stats.new:
        parts.append(f"[green]{stats.new} new[/green]")
    if stats.updated:
        parts.append(f"[cyan]{stats.updated} updated[/cyan]")
    if stats.renamed:
        parts.append(f"{stats.renamed} renamed")
    if stats.archived:
        parts.append(f"[yellow]{stats.archived} archived[/yellow]")
    if stats.settling:
        parts.append(f"[dim]{stats.settling} settling[/dim]")
    if stats.errors:
        parts.append(f"[red]{stats.errors} error(s)[/red]")

    changed = stats.new + stats.updated + stats.renamed + stats.archived
    if changed or stats.errors:
        summary = ", ".join(parts)
        console.print(
            f"[green]✓ Pull complete[/green] — {summary}"
            f"  [dim]· {stats.unchanged} unchanged[/dim]"
        )
    elif stats.settling:
        console.print(
            "[green]✓ Pull complete[/green] — "
            f"[dim]{stats.settling} page(s) recently edited; they'll be written once they settle "
            "(~5 min). Run `notionwiki pull` again shortly.[/dim]"
        )
    elif full:
        console.print(f"[green]✓ Up to date[/green] — {stats.unchanged} page(s), nothing changed.")
    else:
        console.print(
            "[green]✓ Up to date[/green] — no changes since the last pull.  "
            "[dim]Run `notionwiki pull --full` to re-check everything.[/dim]"
        )


@app.command()
def status(
    json_output: bool = typer.Option(False, "--json", help="Machine-readable output"),
) -> None:
    """Ingestion health, last pull time, recent errors (reads daemon_log.md)."""
    if not config_exists():
        console.print("[red]Not initialized.[/red] Run `notionwiki init` first.")
        raise typer.Exit(1)

    config = load_config()
    state_dir = get_state_dir()
    db = StateDB(state_db_path(state_dir))
    try:
        active = [p for p in db.all_pages() if not p.deleted]
        baseline = db.get_meta("last_incremental_baseline")
        full_sweep = db.get_meta("last_full_sweep_at")
    finally:
        db.close()

    log = DaemonLog(daemon_log_path(config.wiki_root))
    recent_errors = [e for e in log.read_entries() if e.action == "error"]

    if json_output:
        typer.echo(
            jsonlib.dumps(
                {
                    "sources": len(active),
                    "last_pull": baseline,
                    "last_full_sweep": full_sweep,
                    "recent_errors": len(recent_errors),
                }
            )
        )
        return

    console.print(f"[bold]{len(active)}[/bold] sources")
    console.print(f"Last pull:       {_humanize_age(baseline)}")
    console.print(f"Last full sweep: {_humanize_age(full_sweep)}")
    if recent_errors:
        console.print(f"[red]{len(recent_errors)} errors[/red] recorded")
        for entry in recent_errors[-5:]:
            console.print(f"  [{entry.timestamp}] {entry.title}: {' | '.join(entry.details)}")
    else:
        console.print("[green]No errors recorded[/green]")


@app.command("open")
def open_command(
    query: str = typer.Argument(..., help="Filename, slug, or title substring to look up"),
) -> None:
    """Print the Notion URL / local path for a source."""
    if not config_exists():
        console.print("[red]Not initialized.[/red] Run `notionwiki init` first.")
        raise typer.Exit(1)

    config = load_config()
    sources = list_raw_sources(config.wiki_root)
    match = find_source(sources, query)

    if match.error == "not_found":
        console.print(f"[red]No source matches[/red] '{query}'.")
        raise typer.Exit(1)

    if match.error == "ambiguous":
        console.print(f"[yellow]Ambiguous match for '{query}' — candidates:[/yellow]")
        for candidate in match.candidates:
            console.print(f"  {candidate.slug}  ({candidate.title})")
        raise typer.Exit(1)

    result = match.result
    console.print(f"Local: {result.path}")
    console.print(f"Notion: {result.notion_url}")


if __name__ == "__main__":
    main()
