"""notionwiki CLI (docs/design.md §8, §8.2). Entry points: `notionwiki`, `nw`."""

from __future__ import annotations

import itertools
import json as jsonlib
import re
import sys
from datetime import UTC, datetime
from pathlib import Path

import typer
from rich.console import Console
from rich.panel import Panel

from notion_wiki import __version__
from notion_wiki.config import Config, DatabaseRef, config_exists, load_config, save_config
from notion_wiki.ingest.daemon_log import DaemonLog
from notion_wiki.ingest.pull import PullRunner
from notion_wiki.notion.client import NotionClient
from notion_wiki.paths import (
    config_path,
    daemon_log_path,
    ensure_wiki_scaffold,
    get_state_dir,
    lock_path,
    state_db_path,
)
from notion_wiki.raw_index import find_source, list_raw_sources
from notion_wiki.schedule.base import detect_scheduler
from notion_wiki.store.db import StateDB
from notion_wiki.token import get_token, set_token

BRAND = "notionwiki"

app = typer.Typer(add_completion=False, no_args_is_help=True)
service_app = typer.Typer(add_completion=False, help="Manage the scheduled notionwiki pull")
app.add_typer(service_app, name="service")
console = Console()


def _humanize_age(iso_timestamp: str | None) -> str:
    if not iso_timestamp:
        return "never"
    then = datetime.fromisoformat(iso_timestamp.replace("Z", "+00:00"))
    now = datetime.now(UTC)
    delta = now - then
    seconds = int(delta.total_seconds())
    if seconds < 60:
        return "just now"
    if seconds < 3600:
        return f"{seconds // 60}m ago"
    if seconds < 86400:
        return f"{seconds // 3600}h ago"
    return f"{seconds // 86400}d ago"


def _status_line(config: Config) -> str | None:
    try:
        db = StateDB(state_db_path())
    except Exception:
        return None
    try:
        count = len([p for p in db.all_pages() if not p.deleted])
        baseline = db.get_meta("last_incremental_baseline")
    finally:
        db.close()
    return f"Status  {count} sources · last pull {_humanize_age(baseline)}"


def _print_banner() -> None:
    lines = [f"[bold]✻ Welcome to {BRAND}[/bold]", "", f"Notion → LLM Wiki bridge · v{__version__}"]
    if config_exists():
        config = load_config()
        lines.append(f"Wiki    {config.wiki_root}")
        status_line = _status_line(config)
        if status_line:
            lines.append(status_line)
    console.print(Panel("\n".join(lines), expand=False))
    console.print()
    console.print(" Try: notionwiki pull        sync from Notion now")
    console.print("      notionwiki graph       open the wiki map at localhost:7777")
    console.print("      notionwiki status      ingestion health")


def _banner_suppressed(argv: list[str]) -> bool:
    """Banner suppression rules (§8.2): never on --json/--quiet/non-TTY output —
    the tool runs unattended, so scheduled pulls must log clean, parseable lines."""
    if "--json" in argv or "--quiet" in argv or "-q" in argv:
        return True
    return not sys.stdout.isatty()


def main() -> None:
    """Console-script entry point. Wraps `app()` to show the welcome banner on the
    bare invocation, `init`, and `--help` (§8.2) — cases Typer's own dispatch
    doesn't give us an easy hook into."""
    argv = sys.argv[1:]
    show_on = not argv or "--help" in argv or "-h" in argv or (argv and argv[0] == "init")
    if show_on and not _banner_suppressed(argv):
        _print_banner()
        if not argv:
            return
    app()


_AGENT_DOC_TEMPLATE = """# {filename}

This is the root of an LLM Wiki fed by notionwiki. Ingestion history lives in
`raw/notion/daemon_log.md`.

## Layers

- `raw/` — Layer 1, immutable source documents. One subfolder per feeder; `raw/notion/` is
  owned by the ingestion bridge and is **read-only to agents by convention**. Cite it via
  `sources: ["[[raw/notion/<slug>]]"]` frontmatter on wiki pages — never edit files under `raw/`.
- `wiki/` — Layer 2, agent-built and agent-owned.
  - `wiki/index.md` — master catalog (generated by `notionwiki graph`)
  - `wiki/graph.json` — link graph (generated by `notionwiki graph`)
  - `wiki/log.md` — narrative operation log (agent-owned)
  - `wiki/overview.md` — high-level synthesis
  - `wiki/concepts/`, `wiki/entities/`, `wiki/sources/` — page types: concept, entity,
    source-summary
- `outputs/` — generated reports/answers: products *of* the wiki, not part of it.

## Rules

- Prefer editing an existing wiki page over creating a near-duplicate; create a new page only
  when no existing page owns the topic.
- Compression rule: a wiki page larger than its source has negative value — synthesize, don't copy.
- Never edit `raw/`. Only the notionwiki ingestion daemon writes there.
- Keep `CLAUDE.md` and `AGENTS.md` as identical twins — mirror an edit to one into the other.

## CLI

`notionwiki pull` (force a sync), `notionwiki status` (ingestion health), `notionwiki graph`
(regenerate index/graph.json + serve the graph UI), `notionwiki open <page>` (look up a source).
There is no `sync`/`push` — this bridge is pull-only.
"""


def _seed_agent_docs(wiki_root: Path) -> None:
    for filename in ("CLAUDE.md", "AGENTS.md"):
        path = wiki_root / filename
        if not path.exists():
            path.write_text(_AGENT_DOC_TEMPLATE.format(filename=filename), encoding="utf-8")


def _extract_page_id_from_url(url: str) -> str:
    stripped = url.replace("-", "")
    match = re.search(r"([0-9a-fA-F]{32})(?:[?#]|$)", stripped)
    if not match:
        return url.strip()
    raw = match.group(1)
    return f"{raw[0:8]}-{raw[8:12]}-{raw[12:16]}-{raw[16:20]}-{raw[20:32]}"


def _database_title(db: dict) -> str:
    return "".join(rt.get("plain_text", "") for rt in db.get("title", [])) or "Untitled database"


def _prompt_root_page(candidates: list) -> tuple[str, str]:
    for i, page in enumerate(candidates, start=1):
        console.print(f"   [{i}] {page.title}")
    paste_index = len(candidates) + 1
    console.print(f"   [{paste_index}] paste a page URL…")
    choice = typer.prompt("   Choice", default="1" if candidates else str(paste_index))
    try:
        idx = int(choice.strip())
    except ValueError:
        idx = paste_index
    if 1 <= idx <= len(candidates):
        page = candidates[idx - 1]
        return page.id, page.title
    url = typer.prompt("   Page URL")
    return _extract_page_id_from_url(url), url


def _prompt_choose_databases(raw_databases: list[dict]) -> list[DatabaseRef]:
    for i, db in enumerate(raw_databases, start=1):
        console.print(f"   [{i}] {_database_title(db)}")
    choice = typer.prompt("   Choose (comma-separated numbers)", default="1")
    indices = {int(part.strip()) for part in choice.split(",") if part.strip().isdigit()}
    return [
        DatabaseRef(id=db["id"], name=_database_title(db))
        for i, db in enumerate(raw_databases, start=1)
        if i in indices
    ]


@app.command()
def init() -> None:
    """Interactive setup wizard (§8.1): wiki location, token, root page, databases, schedule."""
    from notion_wiki.notion.models import Page

    console.print("[bold]notionwiki setup[/bold]\n")

    existing = load_config() if config_exists() else None
    default_root = str(existing.wiki_root) if existing else str(Path.home() / "notionwiki")

    console.print("1. Where should the wiki live?")
    wiki_root = Path(typer.prompt("   Wiki root", default=default_root)).expanduser()

    console.print("2. Paste your Notion internal integration token:")
    token = typer.prompt("   Token", hide_input=True)
    client = NotionClient(token)
    try:
        pages = [Page.from_api(raw) for raw in itertools.islice(client.search(), 10)]
    except Exception as exc:  # noqa: BLE001 - surfaced directly to the operator
        console.print(f"[red]Could not validate token:[/red] {exc}")
        raise typer.Exit(1) from exc
    console.print("   [green]token valid[/green]")

    console.print("3. Which Notion page is the wiki root? (share it with the integration first)")
    root_page_id, root_page_title = _prompt_root_page(pages[:5])

    console.print("4. Also pull databases under it?")
    databases: list[DatabaseRef] = []
    if typer.confirm("  ", default=True):
        raw_databases = list(itertools.islice(client.search_databases(), 25))
        if raw_databases:
            console.print(f"   Found {len(raw_databases)} databases — pull all, or choose?")
            choice = typer.prompt("   [all/choose]", default="all")
            if choice.strip().lower().startswith("c"):
                databases = _prompt_choose_databases(raw_databases)
            else:
                databases = [
                    DatabaseRef(id=db["id"], name=_database_title(db)) for db in raw_databases
                ]

    console.print("5. Pull interval in minutes")
    interval_minutes = max(1, typer.prompt("   Interval", default=1, type=int))

    console.print("6. Install the background schedule now?")
    install_schedule = typer.confirm("  ", default=True)

    config = Config(
        wiki_root=wiki_root,
        root_page_id=root_page_id,
        databases=databases,
        interval_minutes=interval_minutes,
    )
    save_config(config)
    set_token(token)
    ensure_wiki_scaffold(wiki_root)
    _seed_agent_docs(wiki_root)
    client.close()

    console.print(f"\n[green]Wrote config to[/green] {config_path()}")
    console.print(
        f"[green]Scaffolded wiki at[/green] {wiki_root} "
        "(raw/notion/, wiki/, outputs/, CLAUDE.md/AGENTS.md)"
    )

    if install_schedule:
        scheduler = detect_scheduler()
        warnings = scheduler.install(interval_minutes)
        console.print(
            f"[green]Registered[/green] {scheduler.name} schedule (every {interval_minutes} min)."
        )
        for warning in warnings:
            console.print(f"[yellow]Warning:[/yellow] {warning}")

    console.print(
        "\nRun `notionwiki pull` for a first sync, or point your assistant at the wiki root."
    )


@service_app.command("install")
def service_install(
    interval_minutes: int | None = typer.Option(
        None, "--interval", help="Override the configured interval (minutes)"
    ),
) -> None:
    """Register scheduled `notionwiki pull` with the OS scheduler (§10)."""
    if not config_exists():
        console.print("[red]Not initialized.[/red] Run `notionwiki init` first.")
        raise typer.Exit(1)
    config = load_config()
    interval = interval_minutes or config.interval_minutes
    scheduler = detect_scheduler()
    warnings = scheduler.install(interval)
    console.print(f"[green]Installed[/green] {scheduler.name} schedule (every {interval} min).")
    for warning in warnings:
        console.print(f"[yellow]Warning:[/yellow] {warning}")


@service_app.command("uninstall")
def service_uninstall() -> None:
    """Remove the scheduled `notionwiki pull`."""
    scheduler = detect_scheduler()
    scheduler.uninstall()
    console.print(f"[green]Uninstalled[/green] {scheduler.name} schedule.")


@service_app.command("status")
def service_status() -> None:
    """Report whether the scheduled pull is installed."""
    scheduler = detect_scheduler()
    status = scheduler.status()
    if status.installed:
        console.print(f"[green]Installed[/green] ({scheduler.name}): {status.detail}")
    else:
        console.print(f"[yellow]Not installed[/yellow] ({scheduler.name}): {status.detail}")


@app.command()
def daemon(
    interval_seconds: float = typer.Option(
        60.0, "--interval-seconds", help="Pull cadence in seconds"
    ),
    serve_graph: bool = typer.Option(
        False, "--serve-graph", help="Co-host the graph UI in this process"
    ),
    graph_port: int = typer.Option(7777, "--graph-port"),
) -> None:
    """Optional long-lived pull loop (§10) — an alternative to `service install`."""
    if not config_exists():
        console.print("[red]Not initialized.[/red] Run `notionwiki init` first.")
        raise typer.Exit(1)
    config = load_config()
    token = get_token()
    if not token:
        console.print(
            "[red]No Notion token found.[/red] Run `notionwiki init` or set NOTION_WIKI_TOKEN."
        )
        raise typer.Exit(1)

    from notion_wiki.daemon import run_forever

    console.print(f"[green]Running[/green] every {interval_seconds}s (Ctrl+C to stop).")
    run_forever(
        config,
        token,
        get_state_dir(),
        interval_seconds=interval_seconds,
        serve_graph=serve_graph,
        graph_port=graph_port,
    )


@app.command()
def graph(
    serve: bool = typer.Option(False, "--serve", help="Also serve the graph UI at localhost:7777"),
    port: int = typer.Option(7777, "--port", help="Port for the graph UI"),
) -> None:
    """Regenerate wiki/index.md + wiki/graph.json, and optionally serve the graph UI (§9)."""
    if not config_exists():
        console.print("[red]Not initialized.[/red] Run `notionwiki init` first.")
        raise typer.Exit(1)
    config = load_config()

    from notion_wiki.graph.graph_gen import generate_graph
    from notion_wiki.graph.index_gen import generate_index

    generate_index(config.wiki_root)
    graph_data = generate_graph(config.wiki_root)
    console.print(
        f"[green]Regenerated[/green] wiki/index.md and wiki/graph.json "
        f"({len(graph_data['nodes'])} nodes, {len(graph_data['edges'])} edges)."
    )

    if serve:
        from notion_wiki.graph.server import serve as serve_graph

        console.print(f"Serving graph UI at http://127.0.0.1:{port}/graph")
        serve_graph(config.wiki_root, port=port)


@app.command()
def lint() -> None:
    """Agent-run lint pass over the wiki layer (§7): orphans, dangling links, drift."""
    if not config_exists():
        console.print("[red]Not initialized.[/red] Run `notionwiki init` first.")
        raise typer.Exit(1)
    config = load_config()

    from notion_wiki.graph.lint import run_lint

    issues = run_lint(config.wiki_root)
    if not issues:
        console.print("[green]No lint issues found.[/green]")
        return

    console.print(f"[yellow]{len(issues)} issue(s) found:[/yellow]")
    for issue in issues:
        console.print(f"  [{issue.kind}] {issue.page}: {issue.detail}")
    raise typer.Exit(1)


@app.command()
def pull(
    full: bool = typer.Option(False, "--full", help="Force a full reconciliation sweep"),
    json_output: bool = typer.Option(False, "--json", help="Machine-readable output"),
) -> None:
    """Force an immediate pull/convert/write cycle (ingestion)."""
    if not config_exists():
        console.print("[red]Not initialized.[/red] Run `notionwiki init` first.")
        raise typer.Exit(1)

    config = load_config()
    token = get_token()
    if not token:
        console.print(
            "[red]No Notion token found.[/red] Run `notionwiki init` or set NOTION_WIKI_TOKEN."
        )
        raise typer.Exit(1)

    state_dir = get_state_dir()
    client = NotionClient(token)
    db = StateDB(state_db_path(state_dir))
    try:
        runner = PullRunner(
            client,
            config.wiki_root,
            db,
            lock_path=lock_path(state_dir),
            state_dir=state_dir,
        )
        stats = runner.run(full=full, databases=config.database_pairs())
    finally:
        db.close()
        client.close()

    if stats.skipped:
        if json_output:
            typer.echo(jsonlib.dumps({"skipped": True}))
        else:
            console.print("[yellow]Skipped[/yellow] — another notionwiki pull is already running.")
        return

    if json_output:
        typer.echo(
            jsonlib.dumps(
                {
                    "new": stats.new,
                    "updated": stats.updated,
                    "unchanged": stats.unchanged,
                    "renamed": stats.renamed,
                    "archived": stats.archived,
                    "errors": stats.errors,
                }
            )
        )
        return

    console.print(
        f"[green]Pull complete.[/green] new={stats.new} updated={stats.updated} "
        f"unchanged={stats.unchanged} renamed={stats.renamed} archived={stats.archived} "
        f"errors={stats.errors}"
    )


@app.command()
def status(
    json_output: bool = typer.Option(False, "--json", help="Machine-readable output"),
) -> None:
    """Ingestion health, last pull time, recent errors (reads daemon_log.md)."""
    if not config_exists():
        console.print("[red]Not initialized.[/red] Run `notionwiki init` first.")
        raise typer.Exit(1)

    config = load_config()
    state_dir = get_state_dir()
    db = StateDB(state_db_path(state_dir))
    try:
        active = [p for p in db.all_pages() if not p.deleted]
        baseline = db.get_meta("last_incremental_baseline")
        full_sweep = db.get_meta("last_full_sweep_at")
    finally:
        db.close()

    log = DaemonLog(daemon_log_path(config.wiki_root))
    recent_errors = [e for e in log.read_entries() if e.action == "error"]

    if json_output:
        typer.echo(
            jsonlib.dumps(
                {
                    "sources": len(active),
                    "last_pull": baseline,
                    "last_full_sweep": full_sweep,
                    "recent_errors": len(recent_errors),
                }
            )
        )
        return

    console.print(f"[bold]{len(active)}[/bold] sources")
    console.print(f"Last pull:       {_humanize_age(baseline)}")
    console.print(f"Last full sweep: {_humanize_age(full_sweep)}")
    if recent_errors:
        console.print(f"[red]{len(recent_errors)} errors[/red] recorded")
        for entry in recent_errors[-5:]:
            console.print(f"  [{entry.timestamp}] {entry.title}: {' | '.join(entry.details)}")
    else:
        console.print("[green]No errors recorded[/green]")


@app.command("open")
def open_command(
    query: str = typer.Argument(..., help="Filename, slug, or title substring to look up"),
) -> None:
    """Print the Notion URL / local path for a source."""
    if not config_exists():
        console.print("[red]Not initialized.[/red] Run `notionwiki init` first.")
        raise typer.Exit(1)

    config = load_config()
    sources = list_raw_sources(config.wiki_root)
    match = find_source(sources, query)

    if match.error == "not_found":
        console.print(f"[red]No source matches[/red] '{query}'.")
        raise typer.Exit(1)

    if match.error == "ambiguous":
        console.print(f"[yellow]Ambiguous match for '{query}' — candidates:[/yellow]")
        for candidate in match.candidates:
            console.print(f"  {candidate.slug}  ({candidate.title})")
        raise typer.Exit(1)

    result = match.result
    console.print(f"Local: {result.path}")
    console.print(f"Notion: {result.notion_url}")


if __name__ == "__main__":
    main()
